# Generated by Django 3.0.8 on 2020-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200710_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Model',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
