# Generated by Django 3.0.8 on 2020-07-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Model',
            new_name='Contact',
        ),
    ]
