# Generated by Django 3.0.8 on 2020-07-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('order_desc', models.CharField(max_length=10000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
